#!/bin/bash

LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
#GREEN='\033[0;32m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
LT_BLUE='\033[1;36m'
NC='\033[0m'

BIN_DIR="${HOME}"/bin

function CreateLink(){
    if [ ! -L ~/bin/"$2" ]; then
        printf "${LT_BLUE}\n => Creating $1$2 $NC\n"
        ln -s "$1$2" ~/bin/.
    else
        echo -e "${GREEN}\n => ~/bin/$2 already exists! $NC"
    fi
}

clear
printf "${LT_BLUE}Creating Symbolic Links Running...\n"
printf "********************************************${NC}"
if [ ! -d "${BIN_DIR}" ]; then
    printf "${LT_BLUE}\n Creating ${BIN_DIR}.$NC"
    mkdir "${BIN_DIR}"
else
    printf "${GREEN}\n ${BIN_DIR} exists.$NC"
fi

if [ ! -n "$LINNE_SCRIPTS" ]; then
    printf "${LT_BLUE}\n => Creating LINNE_SCRIPTS variable.$NC"
    LINNE_SCRIPTS=$HOME/Git/isit320-linne-2018/linneScripts
    #LINNE_SCRIPTS=$HOME/Git/isit320-linne-2018/linneScripts 
else
    printf "${GREEN}\n => LINNE_SCRIPTS environment variable already exists.$NC"
fi

#printf "${NC}"

CreateLink "${LINNE_SCRIPTS}"/ linne-build-copy

