#!/bin/bash

RED='\033[0;31m'
LT_RED='\033[1;31m'
LT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m'  # NO COLOR

REPO_NAME="$(basename `git rev-parse --show-toplevel`)"

function banner {
    echo ' '
    echo ===============================
    echo --- "$1" ---
    echo ===============================
}

function show {
    banner "$1"
    sudo systemctl show -p ActiveState -p SubState -p Environment $2
}

function showServiceXCheck(){
	show "$1" "$2"
}

function showAll(){
	show week02-rest-basics nrb.service
	show week03-rest-basics02 rbs2.service
	show week05-rest-test rbs2.service
	show week06-system-check systemcheck.service
	show week06-system-check02 systemcheck02.service
	show week07-syscheck-refactor scref.service
	show week09-syscheck-refactor02 scref.service
	show aws-provision awsprov.service
	show practice-syscheck-concur practiceSysCheck.service
	show practice-scref-concur practiceScref.service
	show Midterm midterm.service
}


function checkPorts() {
    sudo nmap -p 30025-30035 ${LOCAL_IP}
}

echo 'System Service Control'

echo 'Learn about Systemd and other running services.'
echo 
while true; do
    printf "${BLUE} Menu\t      Repo: ${LT_GREEN}${REPO_NAME}${BLUE}\n"    
    echo " *********************************************"
    printf "${BLUE} a) Show ALL SystemD Services!\n"
    printf "${LT_GREEN} b) Show week02-rest-basics Service\n"
    printf "${LT_GREEN} c) Show week03-rest-basics02 Service\n"
    printf "${LT_GREEN} d) Show week05-rest-test Service\n"
    printf "${LT_GREEN} e) Show week06-system-check Service\n"
    printf "${LT_GREEN} f) Show week06-system-check02 Service\n"
    printf "${LT_GREEN} g) Show week07-syscheck-refactor Service\n"
    printf "${LT_GREEN} h) Show week09-syscheck-refactor02 Service\n"
    printf "${LT_GREEN} i) Show aws-provision Service\n"
    printf "${LT_GREEN} j) Show practice-syscheck-concur Service\n"
    printf "${LT_GREEN} k) Show practice-scref-concur Service\n"
    printf "${LT_GREEN} l) Show midterm Service\n"
    printf "${LT_RED} x) Exit\n"
    printf "\n$NC"
    read -p " Please make a selection: " userInput
    case $userInput in
		[Aa]* ) showAll; continue;;
        [Bb]* ) showServiceXCheck week02-rest-basics nrb.service; continue;;
        [Cc]* ) showServiceXCheck week03-rest-basics02 rbs2.service; continue;;
        [Dd]* ) showServiceXCheck week05-rest-test rbs2.service; continue;;
        [Ee]* ) showServiceXCheck week06-system-check systemcheck.service; continue;;
        [Ff]* ) showServiceXCheck week06-system-check02 systemcheck02.service; continue;;
        [Gg]* ) showServiceXCheck week07-syscheck-refactor scref.service; continue;;
        [Hh]* ) showServiceXCheck week09-syscheck-refactor02 scref.service; continue;;
        [Ii]* ) showServiceXCheck aws-provision awsprov.service; continue;;
        [Jj]* ) showServiceXCheck practice-syscheck-concur practiceSysCheck.service; continue;;
        [Kk]* ) showServiceXCheck practice-scref-concur practiceScref.service; continue;;
        [Ll]* ) showServiceXCheck Midterm midterm.service; continue;;
        
        [XxQq]* ) break;;
        *) echo -e "\n$NC" + "Please answer with the half of the alphabet shown, or x.";;
    esac
done

