#!/bin/bash

RED='\033[0;31m'
LT_RED='\033[1;31m'
LT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m'  # NO COLOR

LOCAL_IP=$(./get-ip.js)

function checkPorts() {
	printf "${BLUE}nmap -p 30025-30035 ${LOCAL_IP}${NC}\n"
    sudo nmap -p 30025-30035 ${LOCAL_IP}
}

function checkPortRange() {
	printf "${BLUE}nmap -p ${1}-${2} ${LOCAL_IP}${NC}\n"
    sudo nmap -p "${1}"-"${2}" ${LOCAL_IP}
}

echo 'System Service Control'

echo 'Learn about Systemd and other running services.'
echo 
while true; do
    printf "${BLUE} Menu\t\t      IP Addr: ${LT_GREEN}${LOCAL_IP}${BLUE}\n"    
    echo " *********************************************"
    printf "${LT_GREEN} a) Check Ports 30025-30040\n"
    printf "${LT_GREEN} b) Check Ports 1-1023\n"
    printf "${YELLOW} c) Check Ports 1-30024 ${LT_RED}(this may take awhile) \n"
    printf "${LT_RED} x) Exit\n"
    printf "\n$NC"
    read -p " Please make a selection: " userInput
    case $userInput in
        [Aa]* ) checkPorts false; continue;;
        [Bb]* ) checkPortRange 1 1023; continue;;
        [Cc]* ) checkPortRange 1 30024; continue;;
        [XxQq]* ) break;;
        *) echo -e "\n$NC" + "Please answer with a, b, c, or x.";;
    esac
done
