#! /usr/bin/env bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m'  # NO COLOR

SERVER_DIR="${PWD}/../server/public"

function deleteOld() {
    rm -v ${SERVER_DIR}/asset-manifest.json
    rm -v ${SERVER_DIR}/favicon.ico
    rm -v ${SERVER_DIR}/index.html
    rm -v ${SERVER_DIR}/manifest.json
    rm -v ${SERVER_DIR}/precache-manifest*.js
    rm -v ${SERVER_DIR}/service-worker.js

    rm -v -r ${SERVER_DIR}'/static'
}

function copyNew(){
	npm run build
	cp -r build/* ${SERVER_DIR}/.
}

function runAll(){
    deleteOld
    copyNew
}

clear

printf "${YELLOW} Current SERVER_DIR:\n ${SERVER_DIR}\n"

while true; do
    echo -e ${BLUE}" Menu"
    echo " *********************************************"
    printf "${LIGHT_GREEN} a) Delete Old files and run Build\n"
    printf "${LIGHT_GREEN} b) Only Build\n"
    printf "${LIGHT_GREEN} c) Only Delete\n"
    printf "${LIGHT_RED} x) Exit (you should source .bashrc when done)\n"
    printf "\n$NC"
    read -p "Please make a selection: " eotuyx
    case $eotuyx in
        [Aa]* ) runAll false; continue;;
        [Bb]* ) copyNew; continue;;
        [Cc]* ) deleteOld; continue;;
        [XxQq]* ) break;;
        * ) -e "\n$NC" + "Please answer with a, b, c or x(or q).";;
    esac
done
