#! /bin/bash

function copyService() {
    sudo cp -v final-aws-provision.service /etc/systemd/system/.
    sudo systemctl enable final-aws-provision.service
    sudo systemctl start final-aws-provision.service
}

copyService
