#! /bin/bash

function copyService() {
    sudo cp -v awsServerTest.service /etc/systemd/system/.
    sudo systemctl enable awsServerTest.service
    sudo systemctl start awsServerTest.service
}

copyService
