#! /bin/bash

function copyService() {
    sudo cp -v practiceScref.service /etc/systemd/system/.
    sudo systemctl enable practiceScref.service
    sudo systemctl start practiceScref.service
}

copyService
