#! /bin/bash

function copyService() {
    sudo cp -v week05-ec2-copy-file-final.service /etc/systemd/system/.
    sudo systemctl enable week05-ec2-copy-file-final.service
    sudo systemctl start week05-ec2-copy-file-final.service
}

copyService
