#! /bin/bash

function copyService() {
    sudo cp -v rest-basics-final.service /etc/systemd/system/.
    sudo systemctl enable rest-basics-final.service
    sudo systemctl start rest-basics-final.service
}

copyService
