#! /bin/bash

function copyService() {
    sudo cp -v linne-final.service /etc/systemd/system/.
    sudo systemctl enable linne-final.service
    sudo systemctl start linne-final.service
}

copyService
