#! /bin/bash

function copyService() {
    sudo cp -v final-code-aws-provision.service /etc/systemd/system/.
    sudo systemctl enable final-code-aws-provision.service
    sudo systemctl start final-code-aws-provision.service
}

copyService
