#! /bin/bash

function copyService() {
    sudo cp -v final-system-check.service /etc/systemd/system/.
    sudo systemctl enable final-system-check.service
    sudo systemctl start final-system-check.service
}

copyService
