#! /bin/bash

function copyService() {
    sudo cp -v midterm-code.service /etc/systemd/system/.
    sudo systemctl enable midterm-code.service
    sudo systemctl start midterm-code.service
}

copyService
